---
title: "Plotting functions"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lineaGT)
library(magrittr)
library(patchwork)
```

```{r}
data(x.example)
x.example
```


# Scatterplot
```{r}
plots = plot_scatter_density(x.example)
plots$`cov.t2.l1:cov.t1.l2` # to visualize a single plot
```


# Marginal distributions
```{r}
plot_marginal(x.example)
```


# Mullerplot
```{r warning=FALSE}
mp1 = plot_mullerplot(x.example, which="frac")
mp2 = plot_mullerplot(x.example, which="pop")
patchwork::wrap_plots(mp1, mp2, ncol=1)
```



# VAF
```{r}
# plot_vaf(x.example, wrap=T)
```


```{r}
plot_vaf_time(x.example, highlight="C4")
```


# Mullerplot with mutations

```{r warning=FALSE}
mp1 = plot_mullerplot(x.example, which="frac", mutations=T, estimate_npops=T)
mp2 = plot_mullerplot(x.example, which="frac", mutations=T, estimate_npops=F)
patchwork::wrap_plots(mp1, mp2, ncol=1)
```

```{r warning=FALSE}
mp1 = plot_mullerplot(x.example, which="pop", mutations=T, estimate_npops=T)
mp2 = plot_mullerplot(x.example, which="pop", mutations=T, estimate_npops=F)
patchwork::wrap_plots(mp1, mp2, ncol=1)
```


# Phylogenetic evolution

```{r}
plot_phylogeny(x.example)
```



# Clonal Growth
```{r warning=FALSE}
plot_growth_regression(x.example)
```

```{r warning=FALSE}
plot_growth_regression(x.example, highlight="C4", mutations=T)
```


```{r warning=FALSE}
plot_growth_rates(x.example)
```

```{r}
plot_growth_rates(x.example, highlight="C4", mutations=T)
```

